
services:
    db_mysql:
        image: mysql:8.0
        volumes:
            - craftedby_db:/var/lib/mysql
        networks:
            - backend-network
        environment:
            MYSQL_DATABASE: craftedby
            MYSQL_USER: natha
            MYSQL_PASSWORD: natha2013
            MYSQL_ROOT_PASSWORD: natha2013
        ports:
            - "3307:3306"
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "--silent" ]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s

    api_laravel:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - C:\Users\nathalie.soto\craftedby\backend_craftedby:/var/www/html
        depends_on:
            db_mysql:
             condition: service_healthy
        networks:
            - backend-network

volumes:
    craftedby_db:

networks:
    backend-network:
