services:
  traefik:
    image: traefik:v3.1
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/campus/craftedby/acme.json:/letsencrypt/acme.json"
      - "/home/campus/craftedby/traefik.yml:/etc/traefik/traefik.yml"
    restart: always
    networks:
      - backend

  db_mysql:
    image: mysql:8.0
    volumes:
      - craftedby_db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: craftedby
      MYSQL_USER: natha
      MYSQL_PASSWORD: natha2013
      MYSQL_ROOT_PASSWORD: natha2013
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - backend

  api_laravel:
    image: natha2023/backend-craftedby:1.0.2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api_laravel.rule=Host(`api.soto.devlog25.le-campus.eu`)"
      - "traefik.http.routers.api_laravel.entrypoints=http,https"
      - "traefik.http.routers.api_laravel.tls=true"
      - "traefik.http.routers.api_laravel.tls.certresolver=letsencrypt"
      - "traefik.http.services.api_laravel.loadbalancer.server.port=80"
    depends_on:
      db_mysql:
        condition: service_healthy
    environment:
      - FRONTEND_URL=https://www.soto.devlog25.le-campus.eu
      - APP_URL=https://api.soto.devlog25.le-campus.eu
      - SANCTUM_STATEFUL_DOMAINS=https://api.soto.devlog25.le-campus.eu,www.soto.devlog25.le-campus.eu
      - DB_HOST=db_mysql
      - DB_PORT=3306
      - DB_DATABASE=craftedby
      - DB_USERNAME=natha
      - DB_PASSWORD=natha2013
    restart: always
    networks:
      - backend

  app_vue:
    image: natha2023/frontend-craftedby:1.0.5
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app_vue.rule=Host(`www.soto.devlog25.le-campus.eu`)"
      - "traefik.http.routers.app_vue.entrypoints=http,https"
      - "traefik.http.routers.app_vue.tls.certresolver=letsencrypt"
      - "traefik.http.services.app_vue.loadbalancer.server.port=80"
    depends_on:
      - api_laravel
    environment:
      - VITE_API_URL=https://api.soto.devlog25.le-campus.eu/api/
      - VITE_SANCTUM_URL=https://api.soto.devlog25.le-campus.eu/sanctum/csrf-cookie
    networks:
      - backend

volumes:
  craftedby_db:

networks:
  backend:
    driver: bridge


