#name: Build Docker Container
#
#on:
#  push:
#    branches:
#      - main
#      - master
#
#jobs:
#  docker:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
#
#      - name: Build and push
#        uses: docker/build-push-action@v6
#        with:
#          push: true
#          tags: natha2023/backend-craftedby:1.0.3


#name: Build and Deploy Backend
#
#on:
#  push:
#    branches:
#      - main
#      - master
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
#
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v6
#        with:
#          push: true
#          tags: natha2023/backend-craftedby:latest
#
#      - name: Set up SSH agent
#        uses: webfactory/ssh-agent@v0.5.4
#        with:
#          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#
#      - name: copy
#        run: |
#             scp -rp docker-compose.deploy.yaml campus@163.172.178.227:~/craftedby/docker-compose.yaml
#
#      - name: Deploy to server
#        run: |
#            ssh -o StrictHostKeyChecking=no campus@163.172.178.227 '
#            cd ~/craftedby;
#            docker-compose pull api_laravel;
#            docker-compose up -d api_laravel;
#          '

name: Build and Deploy Backend

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx for advanced build capabilities
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub to push images
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # Build and push Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: natha2023/backend-craftedby:latest

      # Set up SSH agent with the provided private key
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Add the server's SSH key to the list of known hosts to avoid prompts
      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H 163.172.178.227 >> ~/.ssh/known_hosts

      - name: donw compose
        run: |
            ssh -o StrictHostKeyChecking=no campus@163.172.178.227 '
            cd ~/craftedby;
            docker-compose down api_laravel
            '

      # Copy the Docker Compose file to the remote server
      - name: Copy Docker Compose file to server
        run: |
          scp -rp docker-compose.deploy.yaml campus@163.172.178.227:~/craftedby/docker-compose.yaml

      # Connect to the server and deploy the Docker container
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no campus@163.172.178.227 '
          cd ~/craftedby;
          docker-compose pull api_laravel;
          docker-compose up -d api_laravel;
          '
